### ISSUE TITLE
UI tasks TODO

### ISSUE THREAD

**Issue by mrrobot16** [api3dao/api3-dao#79]
- [x] review list & check nothing is missing in #77
- [x] find commit of side bar, url verticalBar.
- [x] global stylings before continue 
- [x] screens & components pending from mockups
- [x] tackle list #77 when screens & components done
